include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "flutter_sdk/**"

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    use_super_parameters: true

    # Safety
    avoid_print: true
    cancel_subscriptions: true
    close_sinks: true
    unawaited_futures: true
    unnecessary_await_in_return: true

    # Readability
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_colored_box: true
    use_decorated_box: true
